let const
eomsteve/eomForJavascript pull request #3
Opened 2021-12-14 11:49 UTC by eomsteve

let const 개념을 정리하였습니다.

2021-12-15 10:01 UTC, hokidoki requested changes

2021-12-15 10:01 UTC, hokidoki commented on letConst/README.md
> +es6 이전 자바스크립트는 모든 변수를 var 를 이용해서 선언후 사용했는데, var의 문제점은 언제든 같은 이름의 변수로 재 선언, 재 할당이 가능하기 때문에 의도와 다르게 중복적으로 사용될 여지가 있어 사라졌다.
재 할당 -> 재 선언이 가능합니다.

2021-12-15 13:02 UTC, eomsteve commented on letConst/README.md
> +es6 이전 자바스크립트는 모든 변수를 var 를 이용해서 선언후 사용했는데, var의 문제점은 언제든 같은 이름의 변수로 재 선언, 재 할당이 가능하기 때문에 의도와 다르게 중복적으로 사용될 여지가 있어 사라졌다.
변수를 선언한 뒤 할당, 같은 이름의 변수로 재할당, 재선언이 가능하다 이렇게 말해야 한다는 것인가용?

2021-12-17 00:29 UTC, hokidoki commented on letConst/README.md
> +es6 이전 자바스크립트는 모든 변수를 var 를 이용해서 선언후 사용했는데, var의 문제점은 언제든 같은 이름의 변수로 재 선언, 재 할당이 가능하기 때문에 의도와 다르게 중복적으로 사용될 여지가 있어 사라졌다.
네 맞습니다

2021-12-17 02:55 UTC, hokidoki approved these changes
맥락에서 var의 재 할당 여부가 문제되는 바가 아니라서, 재 할당을 제거 하기를 원했는데 ㅋㅋㅋ 그냥 approve 하겠습니다

2021-12-17 02:55 UTC, merged